name: Update Keys

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch keys
        run: |
          curl -sS "https://raw.githubusercontent.com/protospapers/protospapers/main/keys.json" > keys.json
